package com.upivoicealert.domain.sync

enum class SyncDiagnosticEventType {
    // Sync
    SYNC_STARTED,
    SYNC_COMPLETED,
    SYNC_PARTIAL,
    SYNC_NO_PENDING,
    SYNC_NETWORK_RETRY,
    SYNC_SERVER_RETRY,
    SYNC_VALIDATION_FAILED,
    SYNC_SESSION_EXPIRED,
    SYNC_OFFLINE,
    // Reconciliation
    RECONCILIATION_COMPLETED,
    RECONCILIATION_REPAIRED,
    RECONCILIATION_ERROR,
    // Stale recovery
    STALE_RECOVERY_COMPLETED,
    STALE_UPLOADS_RECOVERED,
    STALE_RECOVERY_ERROR,
    // Integrity audit
    INTEGRITY_AUDIT_HEALTHY,
    INTEGRITY_AUDIT_ISSUES_FOUND,
    INTEGRITY_AUDIT_ERROR,
    // Auth (safe classification only, never tokens)
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILED,
    AUTH_REFRESH_SUCCESS,
    AUTH_REFRESH_FAILED,
    AUTH_REFRESH_REPLAY,
    AUTH_SESSION_EXPIRED,
    AUTH_LOGOUT,
    AUTH_LOGOUT_ALL,
    // Payment pipeline (bounded counters, no PII)
    PIPELINE_NOTIFICATION_RECEIVED,
    PIPELINE_PARSE_REJECTED,
    PIPELINE_VALIDATION_REJECTED,
    PIPELINE_DUPLICATE_DETECTED,
    PIPELINE_PERSISTED,
    PIPELINE_TTS_FAILED,
    // API
    API_SUCCESS,
    API_VALIDATION_ERROR,
    API_AUTH_ERROR,
    API_RATE_LIMITED,
    API_SERVER_ERROR,
    API_NETWORK_ERROR,
    // App health
    APP_HEALTH_OK,
    APP_HEALTH_DEGRADED
}
