package com.upivoicealert.domain.sync

enum class SyncDiagnosticEventType {
    // Sync
    SYNC_STARTED,
    SYNC_COMPLETED,
    SYNC_PARTIAL,
    SYNC_NO_PENDING,
    SYNC_NETWORK_RETRY,
    SYNC_SERVER_RETRY,
    SYNC_VALIDATION_FAILED,
    SYNC_SESSION_EXPIRED,
    SYNC_OFFLINE,
    // Reconciliation
    RECONCILIATION_COMPLETED,
    RECONCILIATION_REPAIRED,
    RECONCILIATION_ERROR,
    // Stale recovery
    STALE_RECOVERY_COMPLETED,
    STALE_UPLOADS_RECOVERED,
    STALE_RECOVERY_ERROR,
    // Integrity audit
    INTEGRITY_AUDIT_HEALTHY,
    INTEGRITY_AUDIT_ISSUES_FOUND,
    INTEGRITY_AUDIT_ERROR
}
